### ISSUE TITLE
Dashboard unavailable after ESPHome version change

### ISSUE THREAD

**Issue by ilium007** [esphome/dashboard#22] opened 2021-06-22 06:33 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome in Docker behind SWAG (https://hub.docker.com/r/linuxserver/swag) reverse proxy.

docker-compose entry:

```
esphome:
    #image: esphome/esphome:1.18.0
    image: esphome/esphome:1.19.2
    container_name: esphome
    networks:
      - ha_network
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
        - /docker/esphome/config:/config
    ports:
      - 6052:6052
    restart: unless-stopped
```

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 / ESP8266
**ESPHome version (latest production, beta, dev branch)**

latest

**Affected component:**

**Description of problem:**

Upgraded Docker image from 1.18.0 to 1.19.0 then 1.19.1 and then 1.19.2. Each time I tried restarting the Docker container but the dashboard UI elements were unresponsive in Safari and Firefox but worked in Chrome. 

I have tried restarting browsers, clearing caches etc but the dashboard remains unresponsive.

All elements are grey, none of the usual link elements respond when clicked.

Safari:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/732766/122875259-5d035300-d377-11eb-9076-f1284632d8a3.png">

Chrome:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/732766/122875444-989e1d00-d377-11eb-91ae-c0c4d2596e6b.png">

If I roll back to 1.18.0 everything works in Safari again:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/732766/122875673-e9157a80-d377-11eb-8250-aef7cc2f4c70.png">

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by balloob** [comment] 2021-06-23 01:50
What version of Safari? And can you test Firefox?

**Comment by ilium007** [comment] 2021-06-23 01:51
Safari: Version 13.1.3 (15609.4.1)

**Comment by balloob** [comment] 2021-06-23 05:13
I only have Safari 14.1.1 (16611.2.7.1.4) locally  on a Mac but am unable to reproduce it. 

I ran it this way:

```
docker run --rm -p 6052:6052 -e ESPHOME_DASHBOARD_USE_PING=true -v "${PWD}":/config -it esphome/esphome
```

In Safari, can you go to develop -> Show JavaScript console and refresh the page. Do you see any errors?

**Comment by OttoWinter** [comment] 2021-06-23 07:11
Related: https://github.com/esphome/issues/issues/2174
Maybe interesting snippet:
> everything works if i go to the ip:port of esphome 192.168.1.xx:6052, it just doesn't work in a frame within home assistant

**Comment by ilium007** [comment] 2021-06-23 10:13
ok... so I left a small bit of info out of the original issue. I run the swag (https://hub.docker.com/r/linuxserver/swag) reverse proxy for esphome dashboard and homeassistant (takes care of my LetsEncrypt SSL certs). If I connect direct to the docker instance on port 6052 it all works.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/732766/123079288-230d7c00-d45f-11eb-921c-1fbfdcea413f.png">

**Comment by ilium007** [comment] 2021-06-23 10:18
> What version of Safari? And can you test Firefox?

Worked in Firefox via the SSL reverse proxy

**Comment by ilium007** [comment] 2021-06-23 10:23
> I only have Safari 14.1.1 (16611.2.7.1.4) locally on a Mac but am unable to reproduce it.
> 
> I ran it this way as per the docs:
> 
> ```
> docker run --rm -p 6052:6052 -e ESPHOME_DASHBOARD_USE_PING=true -v "${PWD}":/config -it esphome/esphome
> ```
> 
> In Safari, can you go to develop -> Show JavaScript console and refresh the page. Do you see any errors?

The only error I see in the Javascript console is this:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/732766/123080954-cb701000-d460-11eb-93f7-7733c6b7d7e5.png">

**Comment by erikpendragon** [comment] 2021-06-23 12:19
i have the same issue, https://github.com/esphome/issues/issues/2174
running safari Version 13.1.2 (13609.3.5.1.5)
javascript console i get 1 error and two warnings

[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. (app.bcb38ac1.js, line 849)
[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. (entrypoint.0d3c68f7.js, line 4171)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (index-7c27abab.js, line 0)

**Comment by balloob** [comment] 2021-06-23 16:50
@erikpendragon there is no authorization on the dashboard so maybe you also forgot to mention that you're running something custom in front of it?

**Comment by erikpendragon** [comment] 2021-06-23 17:09
i have nginx setup as per the add-on instructions with duckdns

domain: '!secret dns_domain'
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf

**Comment by ilium007** [comment] 2021-06-24 01:32
> @erikpendragon there is no authorization on the dashboard so maybe you also forgot to mention that you're running something custom in front of it? 

I run Authelia with SWAG. Authelia provides the authentication for the reverse proxy. It worked fine during the 1.18.0 to 1.19.2 upgrade using Chrome and Firefox, it is only Safari that is causing issues.

**Comment by balloob** [comment] 2021-06-24 03:33
Oh you run Authelia in front of it too? Another "small bit" you forgot to mention.

I am going to take a break from this issue as I feel like I am being sent on a goose chase.

**Comment by ilium007** [comment] 2021-06-24 08:39
> Oh you run Authelia in front of it too? Another "small bit" you forgot to mention.
> 
> 
> 
> I am going to take a break from this issue as I feel like I am being sent on a goose chase.

Nobody has sent you anywhere or on any wild goose chase. I raised the issue in a rush and inadvertently missed these details. It worked in Chrome and Firefox with the nginx reverse proxy / Authelia just not Safari. Enjoy life. Cya.

**Comment by erikpendragon** [comment] 2021-06-25 15:13
mine worked fine before 1.19.x+ as well

**Comment by balloob** [comment] 2021-06-28 04:06
Here is the fix https://github.com/home-assistant/frontend/pull/3259

Feel free to open a PR.

**Comment by erikpendragon** [comment] 2021-06-30 21:08
> Here is how to fix it [home-assistant/frontend#3259](https://github.com/home-assistant/frontend/pull/3259)
> 
> Feel free to open a PR.

i am not sure how this fixes it, it looks to be a code change to the front end. am i expected to pull this myself and request it to be merged back in corrected? how does this issue become a fix?

**Comment by ilium007** [comment] 2021-07-02 11:29
It's been raised here as well: https://github.com/esphome/issues/issues/2174

**Comment by xfader2018** [comment] 2021-07-10 22:54
I have same problem since couple of versions ago.
How to fix it? The link above doesn't really tell how to fix.

**Comment by ilium007** [comment] 2021-07-10 22:55
I changed to Firefox and it’s working again.

**Comment by xfader2018** [comment] 2021-07-10 22:56
Yes, Chrome works also but it should work in Safari as well as it did before.

**Comment by ilium007** [comment] 2021-07-10 22:57
Agree

**Closed** 2022-01-25 20:56 UTC

**Comment by ilium007** [comment] 2022-01-26 00:45
Was this fixed or just closed?
